# Site settings
title:          KatelynPaige
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/katelynpaige"
url:            "https://travjess.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Travis Barlow
  url:          https://github.com/TravJess/travjess.github.io
  email:        aztravjess@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       50

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
